sassoftware/viya4-deployment

README.md

the file in question is called "kustomization.yaml". (and no other name than that will do).

Minor documentation clarification

---

Dockerfile

to address https://github.com/sassoftware/viya4-deployment/issues/25

add aws-iam-authenticator

---

docs/CONFIG-VARS.md
roles/monitoring/defaults/main.yaml

default to stable branch for monitoring

---

roles/vdm/tasks/mirror.yaml
roles/vdm/templates/generators/mirror.yaml

fix container registry mirror

---

roles/vdm/templates/transformers/cas-enable-external-services.yaml

add missing patch

---

Dockerfile
README.md
docker-entrypoint.sh

Update the docker file to allow running as the host user inside the container. This fixes issues with file permissions when running.

Docker user

---

roles/monitoring/files/gcp-storageclass.yaml
roles/monitoring/tasks/main.yaml

- need v4m StorageClass for gcp - tracked via IAC-110

support monitoring for gcp

---

docs/CONFIG-VARS.md
playbooks/playbook.yaml
roles/common/tasks/main.yaml
roles/efs-provisioner/tasks/main.yml
roles/jump-server/defaults/main.yml
roles/jump-server/tasks/main.yml

- add support for JUMP_SVR_RWX_FILESTORE_PATH 
- parse jump_rwx_filestore_path from tfstate
- support for different owner/group for nfs folder permissions.

RWX filestore mount

---

roles/efs-provisioner/defaults/main.yml

update efs provisioner version

---

roles/monitoring/tasks/cluster-logging.yaml
roles/monitoring/templates/user-values-elasticsearch-open.yaml

add annotation to secure kibana ingress

---

roles/baseline/defaults/main.yml
roles/baseline/tasks/cert-manager.yaml
roles/baseline/tasks/contour.yaml
roles/baseline/tasks/ingress-nginx.yaml
roles/baseline/tasks/main.yaml
roles/baseline/tasks/nfs-subdir-external-provisioner.yaml

Add basic support for installing contour during baseline. This will not configure viya to use contour. It is install only

Basic contour install

---

roles/vdm/tasks/elasticsearch.yaml
roles/vdm/tasks/main.yaml

Added additional folder check to ensure elasticsearch is not enable when the order does not include elasticsearch.

add elastic folder check

---

roles/vdm/library/overlay_facts.py
roles/vdm/library/siteconfig_info.py
roles/vdm/tasks/ingress.yaml
roles/vdm/templates/kustomization.yaml

- add support for components
- add support for 2020.1.3+ tls overlays

2020.1.3 tls components support

---

roles/vdm/tasks/connect.yaml

Fix connect transformer being added to orders without connect (V4_CONNECT_FQDN) being set

fix connect-spawer overlay

---

roles/vdm/defaults/main.yaml

switch quoting in variable definition

---

roles/vdm/tasks/deploy.yaml

- add condition to prevent failure when no matching resources are found

add condition to sas.com/admin label blocks

---

roles/vdm/tasks/deploy.yaml

More validation and code changes for `cluster-api` support

Adding in check or rc on error condition

---

roles/monitoring/tasks/cluster-logging.yaml

Working on removing failure guard.

Adjusting failure check for deploy_logging_open.sh script

---

README.md

These updates include a reference to the current status of multi-tenancy support.

Editorial updates to the README

---

roles/vdm/tasks/deploy.yaml

cluster-api : Upating error checking logic

---

docs/CONFIG-VARS.md
roles/baseline/defaults/main.yml

(IAC-470) Remove doc for Ingress-Only TLS
(IAC-445) (IAC-444) Update Ingress-ngnix version and apply CVE Mitigation

Monthly Release - 4.9.0

---

docs/user/Dependencies.md
roles/baseline/defaults/main.yml
roles/baseline/tasks/ingress-nginx.yaml

(IAC-478) Dependencies mismatch to viya4-monitoring-kubernetes #200
(IAC-483) Conditionally Patch ingress-nginx Config #202

Monthly Release - 4.10.0 

---

roles/vdm/tasks/tls.yaml
roles/vdm/templates/generators/customer-provided-merge-sas-certframe-configmap.yaml

(IAC-525) update ansible task for certificate configuration #213
(IAC-525) Update to handle new SAS_CERTIFICATE_GENERATOR default. #211

Monthly Release - 4.12.0

---

Dockerfile

Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/

(IAC-528) added git share directive for viya4-deployment

---

Dockerfile

Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/

(IAC-528) Added git share

---

Dockerfile

(IAC-528) added git share directive for viya4-deployment (#215)
(IAC-528) Added git share (#216)

4.12.1 - April 28, 2022

---

README.md

Updates the "SAS Viya Customizations" section  in the readme.
resolves #229

(IAC-562) Update Kustomize Doc

---

docs/user/Multi-Tenancy.md

Updated the CAS resources and Postgres sections in the README to reflect additional information.

doc: (IAC-441) Updated the CAS resources and Postgres sections

---

roles/vdm/tasks/main.yaml

Reverted the changes for startup sequencer. Changes will be added later after more clarity on the requirements.

feat: (IAC-564): Reverted the changes for sequencer

---

README.md
docs/user/SingleStore.md
roles/vdm/library/siteconfig_info.py
roles/vdm/tasks/main.yaml
roles/vdm/tasks/tls.yaml
roles/vdm/templates/kustomization.yaml

5.3.0 - August 18, 2022

---

Dockerfile
docs/CONFIG-VARS.md
docs/user/Dependencies.md
roles/baseline/defaults/main.yml
roles/monitoring/templates/user-values-prom-operator.yaml

* #286
* #288
* #290
* #287
* #285

5.4.0 - September 01, 2022

---

docs/CONFIG-VARS.md

docs: (IAC-552) Update CONFIG-VARS.md

---

roles/baseline/tasks/ebs-csi-driver.yaml

This is the Helm chart yaml template required to install the ebs csi driver in DAC.
It was left out of the previous PR #298 by mistake.

feat: (IAC-667) add missing Helm chart file required for ebs-csi driver install

---

docs/user/SingleStore.md

Hi Thomas! Here are some edits for this new doc.

(IAC-725) docs: Update SingleStore.md

---

docs/Troubleshooting.md

Add a link to the troubleshooting documentation that leads to the "Initial Troubleshooting" section in the SAS Viya deployment guide.

docs: (IAC-664): Update troubleshoot guide for DO

---

docs/CONFIG-VARS.md

Updates to the Deployment Operator Documentation in CONFIG-VARS.md

docs: (IAC-809) Deployment Operator Documentation Updates

---

README.md

Update the update information in the README

docs: (IAC-743): Add update information in README.md

---

docs/CONFIG-VARS.md

Removed a leftover phrase in the doc, the notes that this section is referring to was moved out into the troubleshooting.md

doc: (IAC-956) Remove Leftover Phrase in Doc

---

docs/Troubleshooting.md

Adds a DAC troubleshooting entry for AWS & GCP non-static kubeconfig files using ansible with orchestration deploy command

docs: (IAC-1028) Troubleshooting entry for AWS & GCP non-static kubeconfig files using ansible with orchestration deploy command

---

Dockerfile
docs/user/Dependencies.md
roles/baseline/defaults/main.yml

Merge stagingplus to staging after rebasing staging to main for 6.6.0 release

---

roles/baseline/defaults/main.yml
roles/common/tasks/main.yaml
roles/multi-tenancy/defaults/main.yml
roles/multi-tenancy/tasks/multi-tenant-setup.yaml
roles/vdm/tasks/deploy.yaml

6.8.0 - June 15, 2023

---

roles/vdm/tasks/deploy.yaml
roles/vdm/tasks/postgres/postgres-instance.yaml

6.9.0 - June 26, 2023

---

Dockerfile
docs/user/Dependencies.md
requirements.txt

6.15.0 - December 12, 2023

---

docs/user/PostgreSQL.md

Remove the "experimental" term from the PostgreSQL doc

docs: (IAC-1304) Remove Experimental from PostgreSQL Doc

---

Dockerfile
docs/CONFIG-VARS.md
docs/user/Dependencies.md
roles/vdm/defaults/main.yaml

6.20.0 - May 17, 2024

---

docs/CONFIG-VARS.md
docs/Troubleshooting.md
docs/user/PostgreSQL.md

Adding sections to the CONFIG_VARS.md, Troubleshooting.md, and PostgreSQL.md files in preparation for the sas-data-server-operator change

docs: (PSKD-615) Documenting upcoming sas-data-server-operator change

---

Dockerfile

Update the Dockerfile so that it can build on both Linux and Mac. Previously, this only worked on Linux environments.

fix: make Dockerfile OS-agnostic (PSKD-1466)

---

README.md
roles/vdm/library/siteconfig_info.py

Provide support to inject sas-bases/overlays entries into the base kustomization.yaml.

feat: support sas-bases/overlays kustomization injections (PSKD-1385)

---

examples/ansible-vars-iac.yaml
examples/ansible-vars.yaml
examples/multi-tenancy/ansible-vars-multi-tenancy.yaml

Add the required `V4_CFG_CADENCE_NAME` and `V4_CFG_CADENCE_VERSION` to the example files

docs: add required cadence variables to examples (PSKD-1296)

---

.github/dependabot.yml
.github/workflows/conventional-commits.yml

Update workflows that were targeting staging. They will now target the main branch.

chore: update workflows to point to main

---

README.md
docs/user/SingleStore.md

docs: (PSCLOUD-126) Update viya4-deployment READMEs to include new SAS SpeedyStore Name

docs: (PSCLOUD-126) Update viya4-deployment READMEs to include new SAS SpeedyStore Name
