sassoftware/viya4-deployment

- roles/ingress-nginx/defaults/main.yml
- Bump ingress nginx chart to 3.20.1 which bump nginx version to 0.43.0
- Update helm values to remove downtime for rolling updates
> bump version and improve rolling updates

- .gitignore
- Dockerfile
- README.md
- docs/DEPENDENCY-VERSIONS.md
- requirements.txt
- requirements.yaml
pins dependencies for openshift, kubernetes, ansible, and community.kubernetes
> #65 additional pip and ansible/ansible-galexy dependency pinning

- examples/sitedefault.yaml
- roles/vdm/files/sitedefault.yaml
sitedefaults.yaml was incorrectly formatted for default admin user. 
Ref SR: [SAS 7613388319]
(was)
```
application:
identities:
sas.identities:
administrator: viya_admin
```
(corrected)
```
application:
sas.identities:
administrator: viya_admin
```
> fix default admin user in sitedefault

- roles/vdm/tasks/tls.yaml
tested with 2021.1.2 (to verify fix) and with 2021.1.4 to make sure it's not breaking more recent version.
> fix front-door tls for pre-2021.1.3 cadence versions

- roles/vdm/tasks/assets.yaml
fixes IAC-319
to test:
specify assets and license file using 
V4_CFG_DEPLOYMENT_ASSETS|V4_CFG_LICENSE
and alternatively with the corresponding docker mounts.
- ideally, use a filename other than license.jwt
- make sure NOT to set V4_CFG_SAS_API_KEY|SECRET. It should not be needed of both deployment assets and license are provided
> pick up user-provided license file

- roles/vdm/tasks/sizing.yaml
- overlays/cas-server/require-cas-label.yaml >= 2021.1.2
- overlays/scaling/single-replica/transformer.yaml >= 2021.1.1
> add cadence control to sizing transformers

- roles/vdm/templates/transformers/sas-storageclass.yaml
make sure that StatefulSets that have no volumeClaimTemplates do not get the sas-ss-storageclass overlay.
fixes #126
fixes #121 
tested by successfully deploying order with both Risk Management and SWO.
> add selector to exclude storageClassName patch from some StatefulSets 

- roles/vdm/tasks/deploy.yaml
- tested against current RTR
- verified that the block does not wait for the timeout if no pods exist
> add cluster-api label support

- roles/monitoring/templates/user-values-elasticsearch-open.yaml
- roles/monitoring/templates/user-values-prom-operator.yaml
- Updated the annotations required for logging and monitoring to work with K8s v1.22
- Verified the changes on Azure with
- K8s v1.22.4 and INGRESS_NGINX_CHART_VERSION: 4.0.13
- K8s v1.19.13 and INGRESS_NGINX_CHART_VERSION: 3.20.1
- Verified the changes on GCP with
- K8s 1.22.3-gke.700 with INGRESS_NGINX_CHART_VERSION: 4.0.13
> (IAC-383) Fixed Logging and monitoring in a K8s 1.22 deployment

- docs/CONFIG-VARS.md
- examples/ansible-vars-iac.yaml
- examples/ansible-vars.yaml
- roles/baseline/defaults/main.yml
- roles/vdm/defaults/main.yaml
- roles/vdm/tasks/tls.yaml
Adds support for the ingress-only TLS Mode which will be available starting in 2021.2.4.
Testing:
Performed a full installation (baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install) to a GCP 1.22.4-gke.1501 & 1.21.6-gke.1500 clusters with the new ingress-only option which resulted in a successful deployment. Verified the ingress type using Gary K's script (see IAC-418 for more details.
> (IAC-418) Add Support For ingress-only TLS Mode

- docs/CONFIG-VARS.md
- roles/vdm/tasks/tls.yaml
changes: added a check for cadence, if below 2021.2.4 & using  ingress-only will quit the playbook early with a meaningful error message.
doc: Add note that ingress-only TLS mode is supported for cadence versions 2021.2.4+
testing:
Performed deployments with ingress-only TLS for various cadences to make sure the task was performing correctly. GCP 1.22.6-gke.300 cluster 
stable: 2021.2.3: task correctly quits the playbook early
stable: 2021.2.4: ingress-only is accepted, the deployment starts
lts: 2021.2: task correctly quits the playbook early
fast: ingress-only is accepted, the deployment starts
> (IAC-418) Update ingress-only TLS Mode Task

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
- (IAC-444) This change updates the default ingress-nginx installed on K8s clusters whose version is <= 1.21.X to version 3.40.0 (appVersion 0.50.0)
- (IAC-445) Also included in this PR is a task that will apply a patch to the ingress-nginx helm chart to mitigate [CVE-2021-25742](https://nvd.nist.gov/vuln/detail/CVE-2021-25742). This patch will automatically be applied to all deployments on clusters whose  version is >= 1.22.X
1. GKE 1.22.4-gke.1501 Cluster
Ran viya4-deployment with a fast:2020 order, all tasks set to install without specifying INGRESS_NGINX_CHART_VERSION (baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install) and waited for Viya, Kibana, & Grafana to stabilize and become usable
ingress-nginx appVersion 1.1.0 was installed. 
2.  GKE 1.21.6-gke.1503 …
> (IAC-445) (IAC-444) Update Ingress-ngnix version and apply CVE Mitigation

- docs/CONFIG-VARS.md
Removing "Ingress-Only TLS" from the doc as this feature is out yet.
> (IAC-470) Remove doc for Ingress-Only TLS

- docs/user/Dependencies.md
Updated kubectl version in Dependencies.md from 1.19.9 to a range 1.20 -1.22 to match the viya4-monitoring-kubernetes expected kubectl version.
Test:
- Created Azure cluster with default kubernetes_version: 1.21.7. Viya4 deployment along with logging and monitoring was successful, no issues found in the process.
> (IAC-478) Dependencies mismatch to viya4-monitoring-kubernetes

- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
The mitigation will be applied by default for K8s clusters whose version is >=1.22.x
and whose ingress-ngnix version is >=1.1.0 or (>=0.50.0 and <1.0.0, for the updated legacy versions of nginx that support this CVE).
Performed deployments in AKS on both 1.22.6 & 1.21.9 clusters to see the CVE mitigation patch behavior. All deployments in this table resulted in a healthy Viya deployment.
| Cadence  | K8s Version | Ingress-Nginx Version                      | Was CVE Mitigation Applied by Default |
|----------|-------------|--------------------------------------------|---------------------------------------|
| 2021.2.5 | 1.22.6      | 1.1.0                                      | Yes                                   |
| 2021.2.4 | 1.22.6      | 1.1.0                                      | …
> (IAC-483) Conditionally Patch ingress-nginx Config

- roles/vdm/templates/generators/customer-provided-merge-sas-certframe-configmap.yaml
Update the `customer-provided-merge-sas-certframe-configmap.yaml` jinja template to handle the new default value for `SAS_CERTIFICATE_GENERATOR` starting in 2021.2.6.
This change makes it so that `SAS_CERTIFICATE_GENERATOR` is set based off the value the user defines for `V4_CFG_TLS_GENERATOR`, rather than falling back to the default.
1. Performed a 2021.2.6 deployment in a 1.22.6 AKS Cluster. Set `V4_CFG_TLS_GENERATOR:cert-manager` and the resulting deployment was successful. Cert-manager was used as the cert generator.
2. Performed a 2021.2.6 deployment in a 1.22.6 AKS Cluster. Set `V4_CFG_TLS_GENERATOR:openssl` as well as the required  variables `V4_CFG_TLS_CERT, V4_CFG_TLS_KEY, V4_CFG_TLS_TRUSTED_CA_CERTS` and the resulting deployment was successful. openssl was used as the cert …
> (IAC-525) Update to handle new SAS_CERTIFICATE_GENERATOR default.

- roles/vdm/tasks/tls.yaml
Update `roles/vdm/tasks/tls.yaml` to correctly apply `cert-manager-provided-ingress-certificate.yaml`. It should only be used if the `V4_CFG_TLS_GENERATOR` is set to cert-manager and the TLS key and Cert are not provided by the user.
Update the customer-provided-merge-sas-certframe-configmap.yaml so that it is correctly applied. It should be used when `V4_CFG_TLS_GENERATOR` is either openssl or cert-manager.
> (IAC-525) update ansible task for certificate configuration

- docs/CONFIG-VARS.md
- roles/vdm/tasks/tls.yaml
- roles/vdm/templates/resources/openssl-generated-ingress-certificate.yaml
Adds support for openssl certificate generator with openssl-generated ingress certificates
See: https://go.documentation.sas.com/doc/en/sasadmincdc/v_026/calencryptmotion/n1xdqv1sezyrahn17erzcunxwix9.htm#p05udr35umjxfrn1xftq9i29bbdk
Verified that the current supported cadence range works with this new addition. See (IAC-540) for more test details.
> (IAC-540) support for openssl certificate generator with openssl-generated ingress certificates

- roles/common/tasks/main.yaml
If the `jump_public_ip` is not present in the `.tfstate` file (The user opted not to create a public IP associated with the jump box) and `jump_private_ip` is present. Ansible will attempt to use that value for `JUMP_SVR_HOST`
Tested in AWS, GCP, and Azure on a 1.21 cluster
1. I first set up my private infrastructure, which includes a bastion host that I will use later to access the jumpbox.
2. Once connected to the bastion host I cloned the IAC project and edited my tfvars to include the following:
```
create_jump_public_ip = false
create_jump_vm        = true
```
* This ensures when my cluster infrastructure is created my jumpbox will not include a public IP address.
3. I ran terraform apply and waited for my cluster infrastructure to come up.
4. In the `terraform.tfstate` file I …
> (IAC-376) Use Private Jump IP if Public not Present in tfstate

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Since our current default version of cert-manager has reached EOL, we are updating the default version to 1.7.2 which is currently supported.
https://cert-manager.io/docs/installation/supported-releases/
Currently supported Viya 4 releases should be compatible with this new default version.
https://go.documentation.sas.com/doc/en/itopscdc/v_026/itopssr/n18dxcft030ccfn1ws2mujww1fav.htm#p0bskqphz9np1ln14ejql9ush824
The following scenarios were tested and showed expected behavior:
| Cadence | CERT\_MANAGER\_CHART\_VERSION | Cloud Provider | K8s Version | TLS Mode | Customer\-Provided\|cert\-manager\-Generated Ingress Certificates  |
|---|---|---|---|---|---|
| 2021\.2\.6 | 1\.7\.2 | GCP | 1\.22\.6\-gke\.1000 | full\-stack | Customer Provided  |
| 2021\.2\.6 | 1\.7\.2 | GCP | …
> (IAC-518) Update Default CERT_MANAGER_CHART_VERSION to 1.7.2

- Dockerfile
- docs/user/Dependencies.md
Because Viya will support K8s 1.21, 1.22 and 1.23 in June 2022, the version of kubectl needs to be bumped up to 1.22 so that it will be in the required -1/+1 range for supported versions of K8s.
|Cloud Provider|kubectl version|K8s version|Cadence|Deployment Stabilized|
|-------|-------|------|-----|------|
|Azure|1.22.10|1.21.9|Fast:2020|Yes|
|Azure|1.22.10|1.21.7|Fast:2020|Yes|
|Azure|1.22.10|1.22.6|Fast:2020|Yes|
|Azure|1.22.10|1.23.5|Fast:2020|Yes|
|AWS|1.22.10|1.22.9|Fast:2020|InProgress |
> (IAC-553) move to kubectl 1.22.10 to support k8s 1.23

- docs/Troubleshooting.md
Update release tag to 5.0.0 in troubleshooting doc to reflect planed release tag value.
Callout github full release names to clarify which repository is being indicated to help avoid confusion.
> fix: (IAC-508) Update release reference in troubleshooting doc

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- roles/vdm/defaults/main.yaml
Makes the new default for `V4_CFG_TLS_GENERATOR` to openssl. Also changes `CERT_MANAGER_ENABLED` to false so cert-manager does not get installed during the baseline by default.
See internal IAC-480 ticket
> feat: (IAC-480) Change default certificate generator to openssl

- roles/baseline/defaults/main.yml
Fix the default `INGRESS_NGINX_CONFIG` so that `annotation` is now correctly `annotations`
More details and artifacts in the internal ticket
1. Created a private cluster using the IAC code and ensured `V4_CFG_INGRESS_MODE` would be set to "private" before running viya4-deployment
2. I adjusted private_ingress annotation variable for azure to include an additional annotation for testing, to mimic the issue reported in IAC-586
* https://github.com/sassoftware/viya4-deployment/blob/main/roles/baseline/defaults/main.yml#L133-L137
4. Ran baseline,install and verified that the ingress-nginx-controller service object correctly contained both of my annotations (proxy-buffering & azure-load-balancer-internal)
```bash
jumpuser@jarpat-pr-byo-jump-vm:/opt/viya4-deployment$ kubectl get service -n …
```
> fix: (IAC-586) Correct the ingress-nginx annotations

- roles/baseline/defaults/main.yml
The baseline role currently defaults V4_CFG_RWX_FILESTORE_ENDPOINT to /export; this is almost certainly meant to be V4_CFG_RWX_FILESTORE_PATH (same as the VDM role).
> (IAC-617) Wrong variable is being defaulted to /export

- roles/vdm/tasks/deploy.yaml
The Viya install steps are being updated in 2022.1.3. The “sas.com/admin=cluster-api” kubectl apply command now includes additional arguments "--server-side --force-conflicts"
See internal IAC-620 ticket
> feat: (IAC-620) Update deploy command to use CRD server-side apply

- roles/vdm/tasks/tls.yaml
For the conditionals that check that "V4_CFG_CADENCE_NAME" in `roles/vdm/tasks/tls.yaml`, it should be case-insensitive.
| Scenario | Cloud | K8s Version | V4\_CFG\_TLS\_MODE | V4\_CFG\_TLS\_GENERATOR | V4\_CFG\_TLS\_\* | V4\_CFG\_CADENCE\_VERSION | V4\_CFG\_CADENCE\_NAME | Error Message |
| -------- | ----- | ----------- | ------------------ | ----------------------- | ---------------- | ------------------------- | ---------------------- | ------------- |
| 1        | Azure | 1.22.6      | full-stack         | openssl                 | not set          | 2020                      | fast                   | none          |
| 2        | Azure | 1.22.6      | full-stack         | openssl                 | not set          | 2020                      | FAST                   | none …
> fix: (IAC-630) Fix the V4_CFG_CADENCE_NAME conditionals in the TLS Task

- roles/vdm/tasks/postgres/postgres.yaml
For the conditionals that check that `V4_CFG_CADENCE_NAME` in `roles/vdm/tasks/postgres/postgres.yaml`, it should be case-insensitive.
| Scenario | Cloud | K8s Version      | Postgres Type | V4\_CFG\_CADENCE\_VERSION | V4\_CFG\_CADENCE\_NAME | Deployment Status |
| -------- | ----- | ---------------- | ------------- | ------------------------- | ---------------------- | ----------------- |
| 1        | Azure | v1.22.6          | external      | 2020                      | FAST                   | stabilized        |
| 2        | Azure | v1.22.6          | external      | 2020                      | fast                   | stabilized        |
| 3        | GCP   | v1.22.9-gke.1500 | internal      | 2020                      | FAST                   | stabilized        |
| 4        | GCP …
> fix: (IAC-630) Fix the V4_CFG_CADENCE_NAME conditionals in the Postgres Task

- roles/monitoring/tasks/cluster-logging.yaml
Removed the kibanaserver, logcollector and metricgetter credentials from "cluster-logging - output credentials" task
- Ran 'cluster-logging, install' task, verified the above credentials were not present as part of output credentials task.
See internal ticket for more details.
> feat: (IAC-568) remove kibanaserver, logcollector and metricgetter id/passwords from "cluster-logging - output credentials" task

- roles/monitoring/tasks/cluster-logging.yaml
- roles/monitoring/tasks/cluster-monitoring.yaml
- roles/vdm/tasks/deploy.yaml
Issue Description:
Reported by Adam Bullock, "a recent deployment with monitoring and logging enabled, that the tls.key in the alertmanager-ingress-tls-secret was incorrect. The certificate was added instead of the key."
The following messages are logged in the ingress-nginx-controller log:
Error obtaining X.509 certificate: no object matching key "monitoring/alertmanager-ingress-tls-secret" in local store Error getting SSL certificate "monitoring/alertmanager-ingress-tls-secret": local SSL certificate monitoring/alertmanager-ingress-tls-secret was not found. Using default certificate
The problematic line: https://github.com/sassoftware/viya4-deployment/blob/main/roles/monitoring/tasks/cluster-monitoring.yaml#L118
Rationale for setting the the delete namespace timeouts to 10 mins is that …
> fix: (IAC-556) Incorrect tls.key in alertmanager-ingress-tls-secret

- roles/vdm/templates/transformers/cas-manage-backup.yaml
- roles/vdm/templates/transformers/cas-manage-workers.yaml
CAS transformers for workers and backup used for default CAS (provider's) are targeting "All" CASDeployments.  For MT deployment, the values in the provider's CAS transformers overwrite the values for tenants' CAS during kustomization ignoring the user specified values for tenants' CAS.
The stale files cas-manage-workers.yaml and cas-manage-backup.yaml were updated to use latest CAS changes.
Deployments were successful for all the scenarios with expected number of workers and backup controllers. See internal ticket for details.
- Multi-tenant MPP deployment with 2 workers and backup controller -> Onboard ACME tenant with 1 worker and 0 backup controller
- (Extended scenario1) Multi-tenant MPP deployment with 2 workers and 1 backup controller -> Onboard ACME tenant with 1 worker and 0 …
> fix: (IAC-645) Updated CAS transformer templates for CAS workers and backup

- roles/multi-tenancy/defaults/main.yml
- roles/multi-tenancy/tasks/multi-tenant-setup.yaml
Originally the default value for V4MT_TENANT_CAS_CUSTOMIZATION was set as null. However, ansible treats 'null' as a valid value for dictionary being defined and tries to run dictionary operations.
Updated the default value for V4MT_TENANT_CAS_CUSTOMIZATION as a empty dictionary.
This specific issue was hit when V4MT_TENANT_CAS_CUSTOMIZATION wasn't provided and ansible used the null value as default.
- Verified with the default changed, the issue was not seen. 
- Ran other combinations with V4MT_TENANT_CAS_CUSTOMIZATION only defined for two out three tenants
- Also verified when V4MT_TENANT_CAS_CUSTOMIZATION  is defined with only tenant names but no customizations.
> (IAC-658): fix: Updating default value for V4MT_TENANT_CAS_CUSTOMIZATION

- README.md
- docs/user/SingleStore.md
- roles/vdm/library/siteconfig_info.py
- roles/vdm/tasks/tls.yaml
- roles/vdm/templates/kustomization.yaml
Add SingleStore README and siteconfig_info change
- Add a link to SingleStore requirements in SAS Viya Operations Guide 2022.1.4
- Add a link to SingleStore README from base README.md to expose it to DAC consumers
- Add additional step and step to skip for sas-bases/examples/sas-singlestore/README.md
- update siteconfig_info to use folder name instead of full path to kustomization.yaml file for component entries
> feat: (IAC-629) Support SingleStore (DAC)

- roles/vdm/tasks/main.yaml
Enabled the startup sequencer feature by referencing the overlay "sas-bases/overlays/startup/ordered-startup-transformer.yaml " in the transformers section of kustomization.yaml before the line that includes "sas-bases/overlays/required/transformers.yaml".
See internal ticket for details. Performed two deployments one with small VA order and another large NA order. Both deployments had stabilization times improved.
> feat: (IAC-564) SAS Viya Startup Sequencer - Add entry in kustomization.yaml

- Dockerfile
- docs/user/Dependencies.md
The default kubectl version value updated to 1.23.8. The supported range is now 1.22x to 1.24x
Deployment was successful for 1.22, 1.23 and 1.24. See the internal ticket for details
> feat: (IAC-673): DAC - support K8s 1.24 deployment

- roles/vdm/templates/transformers/sas-storageclass.yaml
Why:
Release testready orders now include the du sas-data-agent-server-colocated
which does not have /spec/VolumeClaimTemplates in its StatefulSet
resulting in fatal kustomize error during DAC execution. Excluding that du
from the patchTransformer as we've done for two other dus earlier.
> fix: (IAC-689) add new exclusion for storageclass patch transformer

- Dockerfile
- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
To support K8s 1.24, update Ingress NGINX Controller to v1.3.0 (Chart version 4.2.3)
Verified following scenarios, see the internal ticket for details.
1. Viya4 deployment with K8s v1.24.0
2. Viya4 deployment with default K8s v1.23.8
> feat: (IAC-687) Upgrade Ingress-nginx to v1.3.0 to support K8s 1.24

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Update the default `CERT_MANAGER_CHART_VERSION` to 1.9.1 to support K8s 1.24. 
The cert-manager 1.9.x version supports K8s 1.20-1.24 see https://cert-manager.io/docs/installation/supported-releases/.
See artifacts in internal ticket.
| Scenario | Order  | Cadence   | CERT_MANAGER_CHART_VERSION | Cloud Provider | K8s Version      | TLS Mode   | Certificates |
|------------|--------|-----------|----------------------------|----------------|------------------|------------|---------------------------------------------------------------|
| 1          | * | fast:2020 | 1.9.1                      | Azure          | 1.23.8           | full-stack | Customer-Provided                                             |
| 2          | *| fast:2020 | 1.9.1                      | GCP            | …
> feat: (IAC-636) Update cert-manager version 1.9.1

- roles/monitoring/templates/user-values-prom-operator.yaml
A yaml heading (alertManagerSpec) for alert manager didn't match the resource definition heading for alert manager in the helm chart used to deploy it. That mismatch resulted in the V4M_STORAGECLASS configuration variable setting being ignored for alert manager.
> fix: (IAC-670) Correct case typo for alertmanagerSpec

- docs/CONFIG-VARS.md
- examples/ansible-vars-iac.yaml
- examples/ansible-vars.yaml
- roles/vdm/defaults/main.yaml
- roles/vdm/tasks/main.yaml
- roles/vdm/tasks/start_stop.yaml
- roles/vdm/templates/transformers/schedule-start-stop.yaml
Allow the user to configure and include the schedule-start-stop.yaml transformer using the two new variables `V4_CFG_VIYA_STOP_SCHEDULE` & `V4_CFG_VIYA_START_SCHEDULE`. This configures cronjobs in Kubernetes that will start and stop your Viya deployment using the times you specified for these variables. As per the deployment instructions this transformer is prioritized to be placed after `sas-bases/overlays/required/transformers.yaml` in the kustomization.yaml
See internal ticket for more details/artifacts
1. In a 1.23.8 AKS cluster performed a Viya deployment on the latest cadence with `V4_CFG_VIYA_STOP_SCHEDULE: "0 19 * * 1-5"` & `V4_CFG_VIYA_START_SCHEDULE: "30 19 * * 1-5"` set. Verified the positioning of the transformer in the kustomization.yaml. Also verified the Viya deployment …
> feat: (IAC-582) Support configuring schedule-start-stop.yaml

- docs/CONFIG-VARS.md
- roles/vdm/tasks/start_stop.yaml
- roles/vdm/templates/transformers/schedule-start-stop.yaml
Allow the user to specify `V4_CFG_VIYA_START_SCHEDULE` or `V4_CFG_VIYA_STOP_SCHEDULE` rather than requiring both when using the start-stop transformer.
For the variable that the user chooses not to define, the transformer will be updated so the cronjob is set to be suspended. This allows the user to manually trigger the job when needed.
Behavior for other scenarios:
- If both are undefined the transformer is not included at all
- If both are defined they will have the cronjob expressions set as the value and .spec.suspend is false.
Tested out the new scenario by setting `V4_CFG_VIYA_STOP_SCHEDULE` but not `V4_CFG_VIYA_START_SCHEDULE`. The stop job automatically triggered at the scheduled time and the start did not. I was able to manually trigger the start job.
> feat: (IAC-582) Allow user to specify either V4_CFG_VIYA_START_SCHEDULE or V4_CFG_VIYA_STOP_SCHEDULE

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/cert-manager.yaml
Before if a user wanted to use cert-manager in their cluster they need to set two flags: `V4_CFG_TLS_GENERATOR:cert-manager` & `CERT_MANAGER_ENABLED:true`
`V4_CFG_TLS_GENERATOR` controlling the TLS generator that Viya will use, and `CERT_MANAGER_ENABLED` controlling whether or not cert-manager should be installed by the DaC codebase. Even though it is documented to use both, often times user's only set one of these two flags resulting in issues.
This change makes is so that if the user sets `V4_CFG_TLS_GENERATOR:cert-manager`, it will now install cert-manager during the baseline stage, so we no longer need to manage two variables for cert-manager. `CERT_MANAGER_ENABLED` is now removed since setting `V4_CFG_TLS_GENERATOR:cert-manager` provides the same functionality.
More details in …
> feat: (IAC-707) Remove CERT_MANAGER_ENABLED and use V4_CFG_TLS_GENERATOR

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/main.yaml
- roles/common/tasks/main.yaml
Adding support for DAC to install the aws ebs csi driver.
AWS EKS v1.23 and later requires the installation and configuration of the aws elastic block storage csi driver to enable the dynamic provisioning of physical volumes for applications that are configured to use the default storage class.
> feat: (IAC-667) add the ability to install the aws ebs csi driver in DAC

- playbooks/playbook.yaml
For AWS EKS 1.23 or later clusters, cluster-logging, cluster-monitoring, viya and other application components rely upon the ebs csi driver for the dynamic creation of physical volumes.
Those components depend on the ebs csi driver to be resident in the cluster until it is no longer needed.
Prior to this change, all baseline components, including the ebs csi driver would be uninstalled first during the DAC uninstall phase when the baseline component and any other application components were being uninstalled.
After this change, when the baseline and application tags are specified together for uninstall, all application components will be uninstalled prior to the baseline components being uninstalled. Moving the order so baseline components uninstall last will allow the ebs csi driver to …
> feat: (IAC-723) Uninstall baseline components last during uninstall phase

- roles/vdm/tasks/deploy.yaml
- roles/vdm/tasks/mirror.yaml
- roles/vdm/tasks/postgres/gcp-cloud-sql-proxy.yaml
- roles/vdm/tasks/postgres/postgres-instance.yaml
- roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
- roles/vdm/tasks/postgres/postgres.yaml
- roles/vdm/templates/generators/mirror.v2.yaml
- roles/vdm/templates/generators/mirror_v2.yaml
- roles/vdm/templates/generators/postgres-secrets.yaml
- roles/vdm/templates/generators/sql-proxy-serviceaccountkey.yaml
- roles/vdm/templates/postgres-user.env
- roles/vdm/templates/transformers/dataserver-transformer.yaml
- DaC changes related to supporting internal v5 crunchy postgres db.
- Crunchy v5 support for CDS Postgres is still to be added.
- (IAC-724) Update max_connections for Crunchy v5 internal postgres to support Multi-tenancy
- DaC changes related to supporting external crunchy postgres DBs
See internal tickets for details
> feat: (IAC-644) Add DaC support for crunchy v5 

- docs/CONFIG-VARS.md
- roles/vdm/tasks/cds.yaml
- roles/vdm/tasks/main.yaml
- roles/vdm/tasks/planning.yaml
- roles/vdm/tasks/postgres/postgres-instance.yaml
- roles/vdm/tasks/postgres/postgres.yaml
Viya Retail and Planning application require the installation of a secondary PostgreSQL instance referred to as the Common Data Store Postgres instance.
This updates includes the support to install a secondary internal instance of Postgres named "cds-postgres" and can be triggered by including the following postgres clause in the ansible-vars.yaml file used to deploy Viya.
```yaml
V4_CFG_POSTGRES_SERVERS:
default:
internal: true
cds-postgres:
internal: true
```
Testing included deploying a fast 2020 Inventory Fulfillment Viya order while specifying two Postgres instances as above. The presence of planning application schemas created in the CDS Postgres instance were used to verify the successful deployment and configuration of the CDS Postgres instance.
> feat: (IAC-739) Support a CDSPostgreSQL instance for Crunchy v5

- docs/user/Multi-Tenancy.md
- roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
- Updated crunchy v5 tuning transformer. The variables and format of the tuning transformer used previously to add max_connections changed, made changes to accommodate these changes.
- Minor change to onboard run command for parity with other commands (this was somehow missed previously).
Verified the new tuning transformers are generated correctly for both platform postgres and cds postgres.
> feat: (IAC-756): Update crunchy v5 tuning transformer

- roles/common/tasks/main.yaml
When performing a deployment in GKE, the new tasks add the GKE pod subnet cidr to `LOADBALANCER_SOURCE_RANGES` to allow for N/S traffic
Additional details are contained in internal ticket
Updated viya4-iac-gcp and viya4-deployment, gke_pod_subnet_cidr is automatically added to LOADBALANCER_SOURCE_RANGES
Order: ***, Cadence: fast:2020, kubernetes version: 1.23.8-gke.1900
Once gke_pod_subnet_cidr was added to the LOADBALANCER_SOURCE_RANGES N/S was allowed and I was able call a Viya service via the ingress-nginx hostname
Input Validation Scenarios
Order: ***, Cadence: fast:2020, kubernetes version: 1.23.8-gke.1900
1. gke_pod_subnet_cidr already in LOADBALANCER_SOURCE_RANGES (user added in ansible-vars.yaml)
2. provider not in terraform.tfstate as an output
3. provider is not "gcp" as an …
> feat: (IAC-557) Add GKE pod subnet cidr to LOADBALANCER_SOURCE_RANGES

- examples/sitedefault.yaml
- roles/vdm/files/sitedefault.yaml
Updated the sitedefault.yml file to include required missing ldap.connection.url property and the suggested format for define admin user `config/identities/sas.identities/administrator: viya_admin`
Ran viya4-deployment at least 3 times and verified the `viya-admin` user was prompted the SASAdministrator role. See details in internal ticket.
> fix: (IAC-524): Modify sitedefault.yml file to include required missing ldap.connection.url property

- roles/baseline/tasks/main.yaml
- roles/common/tasks/main.yaml
Instead of pulling the K8S server version information from an output passed in from tfstate, query the K8s server version from within DAC to remove a dependency on IAC to provide it in the AWS provider, or other providers in the future. This change should allow viya4-iac-aws releases prior to 5.2.0 to work with the latest DAC release just as before.
Verification of this update will be run against clusters created by each IAC project.
Internal ticket comments contain dev test results with this update run against clusters created by all four IAC projects.
> fix: (IAC-742) Lookup cluster K8S version information from within DAC

- docs/CONFIG-VARS.md
- roles/vdm/templates/transformers/crunchy-storage-transformer.yaml
Change the default storage class name to use for postgres and pgbackrest PVCs to 'sas', a storage class  which DAC normally creates for each of the cloud environments.
Scenarios run against Azure, AWS and GCP point to the need for this change in AWS and GCP cloud environments.
> (iac-701) Use 'sas' as default storage class name for postgres and pgbackrest PVCs

- docs/user/Dependencies.md
Docker needs to be >=20.10.10 to run ubuntu:21.10 or later containers.
ref: https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921
> docs: (IAC-552): Update Dependencies.md for min Docker Version

- roles/vdm/tasks/assets.yaml
- roles/vdm/tasks/deploy.yaml
- roles/vdm/tasks/orchestration.yaml
- roles/vdm/templates/generators/sas-license.yaml
The addition of "license" folder, this will live underneath the DEPLOY_DIR and it will contain the certs and license.jwt file. The license.jwt currently exists under site-config. This is so the structure is more in line in the SAS Documentation.
Swapped out the usage of `community.docker.docker_container` to run the orchestration docker container to instead use `ansible.builtin.shell`. The older module did not have a way to split stdout from stderr and included lines we did not need in the generated CRD .
See internal ticket.
| Scenario | Provider | K8s Version | Order | Docker | Cadence | DO Enabled | Deployment Stabilized  |  
|---|---|---|---|---|---|---|---|
| 1 | Azure | v1.23.8 | * | With Docker | stable:2022.11 | yes | yes  |  
| 2 | GCP | v1.24.4-gke.800 | *| With Docker | …
> feat: (IAC-664) Update Docker Run Calls and Create License Folder

- roles/vdm/tasks/postgres/pg_config.yaml
Substitute using an ansible kubernetes.core.k8s_info module query as opposed to the builtin.shell "kubectl | grep" command to avoid generating "red" Ansible error output that requires ignoring and can cause questions or concerns for end users.
Ran through a deployment with Viya uninstalled and two separate redeployments against clusters with v4 crunchy installed and a redeployment on a cluster with v5 crunchy installed to verify that the v4_crunchy_present fact was being set properly to true or false for the version of crunchy installed.
> feat: (IAC-770) use k8s.core.k8s_info module not kubectl to avoid ansible error output

- README.md
There was some confusion around the users and groups added in the embedded OpenLDAP not being persisted. Updated the README to provide some clarification about the same.
> docs: (IAC-560): Added clarification on the users added to the embedded OpenLDAP

- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
With the CLB retiring, this change will enable NLB as the default load-balancer that gets deployed for AWS.
Verified following scenarios on AWS EKS cluster. See details in internal ticket:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|Defaults, no additional annotations|Fast 2020|NLB load-balancer was created. Viya4 deployment stabilized and was accessible|
|2|Specified additional annotations|Stable 2022.11|NLB load-balancer was created along with the additional annotations. Viya4 deployment stabilized and was accessible|
|3|Specified additional annotations along with aws-load-balancer-type: nlb|Fast 2020|NLB load-balancer was created along with the additional annotations. NLB annotation wasn’t duplicated. Viya4 deployment stabilized and was accessible|
> feat: (IAC-439): Make NLB to be default load balancer for AWS

- roles/vdm/tasks/storage.yaml
The kustomization.yaml file placement for the sas-storageclass.yaml transformer in DAC needs to occur prior to the user injected transformer files that a DAC user can include under a site-config/\<folder\> location.
Prior to this update, if a DAC user includes the sas-common-backup-data-storage-class-transformer.yaml transformer under a site-config/\<folder\>, it will appear in kustomization.yaml prior to sas-storageclass.yaml, and is unable to modify the storage class name as needed.
Moving DAC's placement of sas-storageclass.yaml up to the transformer (pre) section resolves that issue and allows a user specified transformer to update the storage class name used for backups as expected.
Run through a DAC deployment with the sas-common-backup-data-storage-class-transformer.yaml placed …
> fix: (iac-602) sas-common-backup-data-storage-class-transformer sequence issue

- roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
- roles/vdm/templates/kustomization.yaml
Update the indentation in the kustomization.yaml file so it's more in line with the SAS documentation.
See: https://go.documentation.sas.com/doc/en/sasadmincdc/v_035/dplyml0phy0dkr/n0g237aqo6pz1in1t19wjb94j9bi.htm#n08dvkro120s4on1g8wbqxpbcspt 
After updating the indentation in our kustomization.yaml template, I ran through the following scenarios to verify that the generated kustomization.yaml file now has spacing that matches the SAS documentation and that Viya still deploys correctly.
I specifically ran through a MT scenario since we have some logic that does regex operations on the kustomization.yaml when onboarding/offboarding tenants
| Scenario | Cloud | K8s Version     | Deploy Method | Orchestration | Order  | Cadence   | Notes         | …
> feat: (IAC-693) Update kustomization.yaml indentation

- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
Reverting the changes previously made in PR #349.
**Reason for reverting:** There are few other LBs in DaC namely, V4_CFG_CAS_ENABLE_LOADBALANCER, V4_CFG_CONNECT_ENABLE_LOADBALANCER, V4_CFG_CONSUL_ENABLE_LOADBALANCER. These LBs still seem to be creating the CLB instead of NLB need to readdress the ticket and make sure all the LBs are shifted to using NLB.
> feat: (IAC-439): Revert NLB changes

- roles/vdm/tasks/storage.yaml
- roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
- roles/vdm/templates/transformers/compute-server-add-nfs-mount.v2.yaml
- roles/vdm/templates/transformers/launcher-nfs-mount.yaml
- Refresh CAS and compute storage related transformers with the latest versions
- Remove nfs-homes patch from compute-server-add-nfs-mount transformer in .v2 version, now handled by launcher-nfs-mount transformer
- Use launcher-nfs-mount transformer with updated compute nfs-homes support in favor of launcher-service-add-nfs transformer 
- Use NFS server filestore homes path in cas-add-nfs-mount transformer allowing CAS access to nfs-homes volume
- Use and apply the updated transformers with the latest SAS Viya LTS version that provided support for them
Following the steps documented in [SAS Viya: making user home directories available to compute](https://communities.sas.com/t5/SAS-Communities-Library/SAS-Viya-making-user-home-directories-available-to-compute/ta-p/717561?lightbox-message-im …
> feat: (IAC-720) Update \site-config\vdm\transformers with sas-bases\examples

- docs/Troubleshooting.md
Adds troubleshooting documentation around Docker requirements when you are running this project directly on your host rather than using the docker container.
As of [release 6.0.0](https://github.com/sassoftware/viya4-deployment/releases/tag/6.0.0), it's required that if you are running this project using Ansible directly on your workstation, it needs Docker to be installed and the executing user should be able to access it. This is so that we can consume the [sas-orchestration tool](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvln1pzpcxa68tpom.htm#p1garxk7w4avg2n1hd6e4nt5kks7), which is available as a Docker image to generate the [SASDeployment Custom Resource file](https://go.documentation.sas.com/doc/en/itopscdc/default/dplyml0phy0dkr/p0nid9gu3x2cvl …
> docs: (IAC-894) Add troubleshoot documentation around docker requirements.

- Dockerfile
- docs/user/Dependencies.md
- roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
- roles/multi-tenancy/tasks/multi-tenant-setup.yaml
- roles/vdm/tasks/main.yaml
- roles/vdm/tasks/validations.yaml
* Updated the default version of kustomize in the Dockerfile to 4.5.7 since 2023.02 will now requires that
* Conditional statements added to switch between 3.7.0 & 4.5.7 versions of the command depending on the SAS cadence you will be deployinh
* Added kustomize version validation based om cadence.
Validated that the correct flag was used per kustomize command depending on version, and ensured a warning was thrown if the wrong version was present.
The default version of kustomize in the dockerfile is now 4.5.7 and the user can still override the version when building the image using the flag `--build-arg kustomize_version=3.7.0` in conjunction with docker build (This is existing documented behavior.)
| Scenario | Task                                | V4_DEPLOYMENT_OPERATOR_ENABLED | …
> feat: (IAC-849) Updates for Kustomize 4.5.7

- roles/vdm/tasks/validations.yaml
Fix the kustomize error message. The correct message should be:
```
When deploying the SAS Viya Platform on cadence versions <= 2023.01 you must have
```
> fix: (IAC-849) Fix Kustomize Error Message

- roles/vdm/tasks/postgres/postgres-instance.yaml
- roles/vdm/tasks/postgres/postgres.yaml
- roles/vdm/templates/transformers/dataserver-transformer.yaml
- roles/vdm/vars/main.yaml
Along with the Crunchy 5 changes made in 2022.10, a blanket support statement was made that CDS Postgres should be internal only. Other teams now want to use CDS externally so allow DAC to configure and deployments to use external default and cds-postgres PostgreSQL instances for 2022.12 cadence and later.
- Change message boundary to pre 2022.12 cadences for cds-postgres instance must be internal only
- Generate user.env, secrets generator and dataserver-transformer for an external cds-postgres instance
- Modify dataserver-transformer template so that it can generate sas-platform-postgres-dataserver-transformer and sas-cds-postgres-dataserver-transformer outputs with expected dataserver names
- Include cds-postgres overlay for an external cds-postgres instance
- Use SharedServices as …
> feat: (IAC-878) support external cds postgres

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Updated the default cert-manager version (`CERT_MANAGER_CHART_VERSION`) to 1.11.0
This new version is compatible with K8s 1.21 → 1.26, this version should work with all supported Viya cadences that are able to deployed on that K8s version range.
Ran through the following scenarios to test the updated cert-manager version
| Scenario | Task                      | Provider | Cadence        | K8s Version          | V4_CFG_TLS_GENERATOR | V4_CFG_TLS_MODE | V4_CFG_TLS_CERT/KEY/TRUSTED_CA_CERTS | Deployment Method |
|----------|---------------------------|----------|----------------|----------------------|----------------------|-----------------|--------------------------------------|-------------------|
| 1        | OOTB + Logging Monitoring | Azure    | fast:2020      | v1.24.9              | …
> feat: (IAC-874) Update default cert-manager version to 1.11.0

- roles/baseline/defaults/main.yml
The update made to the default value for V4_CFG_MANAGE_STORAGE in #334 impacted the viya based install tasks. The default for that variable should have also been added to the baseline defaults so that the baseline tasks will behave as if V4_CFG_MANAGE_STORAGE=true if it is not specified as a configuration variable in ansible-vars or with command line flags. Adding the default value of V4_CFG_MANAGE_STORAGE=true as a baseline default value allows for the creation of the "sas" and "pg-storage" storage classes during the "baseline,install" task as the default behavior as intended with #334.
Behavior prior to this update
| Scenario | DAC version | Method | V4_CFG_MANAGE_STORAGE | DAC tags| storage class install,uninstall results | Expected result |
|-|-|-|-|-|-|-|
| 1 | 6.2.0-staging image | …
> fix: (IAC-909) storageClasses not created during baseline install w/out V4_CFG_MANAGE_STORAGE explicitly defined

- roles/vdm/tasks/postgres/postgres-multi-tenant-config.yaml
Postgres has split the tuning transformers `crunchy-tuning-transformer.yaml` which was used for adjusting the max_connections for tenants and enabling/disabling the TLS for front-door TLS on Multi-tenant enabled deployments.
In this change the support for separate transformers has been added for SAS Viya Platform cadence version 2023.03 and above. The new transformers are:
- For adjusting max_connection: `crunchy-tuning-connection-params-transformer.yaml`
- For TLS options front-door/disabled: `crunchy-tuning-pg-hba-no-tls-transformer.yaml`
Verified following scenarios. For details see the internal ticket:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|TLS: full-stack with schemaPerTenant mode | Fast 2020 |New transformer for connections update was created. …
> feat: (IAC-912): Postgres tuning transformer changes for 2023.03 cadence

- docs/CONFIG-VARS.md
- docs/Troubleshooting.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/cluster-autoscaler.yaml
- roles/baseline/tasks/main.yaml
Since the 2023.03 cadence adds support for K8s 1.25, we want to add support for that version across all the IAC projects. The usual process for this is just bumping the kubernetes_version & kubectl values so that we are in the +1/-1 range of all the versions the latest cadence supports.
Upon using viya4-deployment to baseline a 1.25 EKS cluster we ran into an issue installing the cluster-autoscaler, we needed to update it to a version that supports `PodDisruptionBudget policy/v1` since `policy/v1beta1` was deprecated as of 1.25. The new default `CLUSTER_AUTOSCALER_CHART_VERSION` we use for 1.25+ clusters is version 9.25.0. With the update to the autoscaler version we also needed to make changes on the viya4-iac-aws side to support this new version, updates were made to the …
> feat: (IAC-903) Update Cluster Autoscaler for EKS 1.25 Support

- roles/monitoring/defaults/main.yaml
A default value for V4_CFG_MANAGE_STORAGE is required for viya4-deployment monitoring tasks so DAC will behave as if V4_CFG_MANAGE_STORAGE=true has been set even if it is not specified as a configuration variable in ansible-vars or with command line flags. Adding the default value of V4_CFG_MANAGE_STORAGE=true as a monitoring task default value allows V4M logging and monitoring applications to successfully install/uninstall as expected when V4_CFG_MANAGE_STORAGE=true is not explicitly defined.
Behavior prior to this update
| Scenario | DAC version | Method | V4_CFG_MANAGE_STORAGE | DAC tags| monitoring install,uninstall results | Expected result |
|-|-|-|-|-|-|-|
| 1 | DAC 6.2.0 image | docker | not present | "cluster-logging,install" | v4m - add storageclass task fails, DAC exits with …
> fix: (IAC-917) cluster_logging install fails when V4_CFG_MANAGE_STORAGE is not explicitly defined

- roles/vdm/templates/transformers/cas-add-nfs-mount.yaml
Revert the unnecessary change to the nfs-data mountPath made [here](https://github.com/sassoftware/viya4-deployment/pull/366/files#diff-e18bf8b7b885bce91ca13a90fd4bca20d3e9d3eeaa8d6563437386229eb49b8aR35-R36) in PR #366
The original nfs-data mountPath of /mnt/viya-share/data in the cas-add-nfs-mount.yaml transformer should  be restored with this change.
The originator of IAC-932, Jerry Read, will try out this update to verify that the previous mountPath value is restored with this update.
Jerry used the f-iac-932 development branch to run DAC with DEPLOY=false and has confirmed that the cas-add-nfs-mount transformer generated from the updated template uses the restored mountPath for nfs-data.
> fix: (IAC-932) restore previous nfs-data mountPath in cas-add-nfs-mount.yaml transformer

- roles/multi-tenancy/tasks/main.yaml
- roles/orchestration-common/tasks/orchestration_tooling.yaml
In PR #395 code was updated to utilize kustomize from within the sas-orchestration image for all tasks, however "onboard" tag was missing from the new tasks in `orchestration-common/tasks/orchestration_tooling.yaml`. This resulted in Multi-tenant onboard command failure: `ORCHESTRATION_TOOLING_DIRECTORY is undefined`.
This change fixes the above issue by adding the missing tag "onboard" to the orchestration_tooling tasks.
Verified following scenarios, see details in internal ticket:
|Scenario|Task|Cadence|K8s Version|Execution Method|Orchestration|
|:----|:----|:----|:----|:----|:----|
|1|OOTB + Multi-Tenant|stable:2023.02|v1.25|Docker|Deploy Command|
|2|OOTB + Multi-Tenant|Fast:2020|v1.24|Ansible|Deployment Operator|
> fix: (IAC-953): Fixed multi-tenant onboard command failure

- playbooks/playbook.yaml
- roles/baseline/tasks/main.yaml
- roles/common/tasks/main.yaml
- roles/monitoring/tasks/main.yaml
The entry for V4_CFG_MANAGE_STORAGE in CONFIG-VARS.md indicates that it defaults to true but is not required. This PR ensures that if a value for V4_CFG_MANAGE_STORAGE has not been defined in ansible-vars or via a command line flag, it will be set to true. Validation checks were added to fail and exit with a message for empty or unsupported values.
Verified these scenarios, see internal ticket for additional details:
| Scenario | Method | Description | tags | Order | Verification |
|:-|:-|:-|:-|:-|:-|
| 1 | ansible | V4_CFG_MANAGE_STORAGE not defined in ansible-vars and not specified on command line | "baseline,cluster-monitoring,install" | 2023.02 | DAC sets V4_CFG_MANAGE_STORAGE=true, nfs-subdir-external-provisioner creates both storageClasses, v4m storage class is created |
| 2 | …
> fix: (IAC-938) filestore directory doesn't get created w/o V4_CFG_MANAGE_STORAGE

- docs/CONFIG-VARS.md
- roles/vdm/tasks/deployment_operator.yaml
The `DEPLOY` variable should now also control the install/uninstall of the deployment operator, see table below for behavior changes.
|                                  | viya,install DEPLOY:True | viya,install DEPLOY:False | viya,uninstall DEPLOY:True | viya,uninstall DEPLOY:False                     |
| -------------------------------- | ------------------------ | ------------------------- | -------------------------- | ----------------------------------------------- |
| Deployment Operator - Deployment | Deployed                 | Deployed                  | Deleted                    | Deleted                                         |
| Deployment Operator - Namespace  | Created                  | Created                   | Deleted                    | Deleted …
> feat: (IAC-920) DEPLOY Flag Should Also Control the Deployment Operator Un/Installation

- docs/user/AnsibleUsage.md
Added documentation around the `ansible.cfg` file and how to load it when running `ansible-playbook` from outside of the project's directory.
> docs: (IAC-961) Ansible Config Documentation

- README.md
Update the README list for tasks that viya4-deployment can perform to include installation of the aws-ebs-csi-driver for AWS only. Also add the (AWS only) annotation to installation of the metrics-server as that is currently the only cloud provider that viya4-deployment installs that on.
This README update was initially associated with IAC-891. IAC-891 was used to update external SAS documentation so IAC-954 was opened to track this README change.
> docs: (IAC-954) Add aws-ebs-csi-driver entry to "Prepare Kubernetes Cluster" list in README

- docs/Troubleshooting.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
For Users upgrading their AKS cluster's Kubernetes version to 1.24 (or later) and used viya4-deployment v6.3.0 (or prior) for the SAS Viya Platform deployment were unable to access the SAS Viya Platform WebApps.
This issue is related to Azure LoadBalancer’s probing. The appProtocol support inside cloud provider has broken ingress-nginx for AKS clusters >=1.22. The issue was caused by two reasons:
* the new version of nginx ingress controller added appProtocol and its probe path has to be `/healthz`;
* the new version of cloud-controller-manager added HTTP probing with default path `/` for appProtocol=http services.
To resolve this issue the ingress-nginx version should be 1.3.0 (or later) with the following annotation configured :
> --set …
> feat: (IAC-893) Ingress-nginx service annotation added for Azure LB probing issue

- docs/Troubleshooting.md
Adds troubleshooting documentation providing the symptom and resolution for a kustomize error users might encounter while deploying the SAS Viya Platform with viya4-deployment releases prior to 5.4.0.
The remedy for users that run into this problem is to use viya4-deployment [release 5.4.0](https://github.com/sassoftware/viya4-deployment/releases/tag/5.4.0) or later.
> docs: (IAC-930) sas-data-agent-server-colocated statefulset caused "/spec/volumeClaimTemplates/0/spec/storageClassName": missing value during update

- docs/CONFIG-VARS.md
Adds requested instructions for setting `V4M_STORAGECLASS` value to `local-storage` in ansible-vars.yaml when using [viya4-deployment](https://github.com/sassoftware/viya4-deployment.git) to deploy `cluster-logging` and `cluster-monitoring` applications on kubernetes clusters provisioned with the [open source kubernetes IaC](https://github.com/sassoftware/viya4-iac-k8s) project
> docs: (IAC-916) V4M monitoring and logging fails to install with open-source K8s because of the missing v4m SC

- docs/user/SingleStore.md
The DAC SingleStore.md has a [section](https://github.com/sassoftware/viya4-deployment/blob/bc2992bc6f79630678d259a1fcfbf79a2bb18e14/docs/user/SingleStore.md#deploying-sas-viya-with-singlestore-using-sas-viya-4-deployment) for Deploying SAS Viya with SingleStore Using SAS Viya 4 Deployment.    It mentions using viya4-iac-azure.  We need to add viya4-iac-aws and viya4-iac-k8s.
> docs: (IAC-958) update DAC SingleStore.md to include iac-aws and oss-k8s

- Dockerfile
Fixes issue #414
- Update helm version used in docker image from 3.8.1 to 3.9.4
- Rebuild docker image with the latest ubuntu 22.04 image available from docker hub
- Rebuilt the viya4-deployment docker image with helm 3.9.4 using the docker build --no-cache option to enforce pulling the latest ubuntu 22.04 ([jammy-20230308](https://hub.docker.com/layers/library/ubuntu/jammy-20230308/images/sha256-7a57c69fe1e9d5b97c5fe649849e79f2cfc3bf11d10bbd5218b4eb61716aebe6?context=explore)) image from docker hub
- Used docker scout CLI tool to verify the list of critical CVEs present in the existing viya4-deployment:6.3.0 image
- Re-ran docker scout against the rebuilt viya4-deployment docker image to verify that no critical CVEs are present in it
viya4-deployment development tests, see internal …
> fix: (IAC-960) Remediate DAC critical vulnerabilities

- docs/CONFIG-VARS.md
- docs/Troubleshooting.md
- roles/orchestration-common/tasks/orchestration_tooling.yaml
Changes were made to how the task that parses the default credentials from `{{ DEPLOY_DIR }}/sas-bases/base/secrets.yaml`, we now are  properly escaping parsed credentials to handle the case where they may contain Jinja2 special characters. Documentation was also added to tell users to add the `!unsafe`  denotation who have special Jinja2 character sequences in credentials the put in their ansible-vars. This tells ansible not to "templatize" the values.
**Methodology:**
The task that parses and incorrectly escapes credentials with special [Jinja2 characters](https://jinja.palletsprojects.com/en/2.11.x/templates/#synopsis) is  `orchestration tooling - set registry credentials if using defaults`. This task will only run if a user did not define …
> fix: (IAC-956) Handle Special Characters for Orchestration Credentials

- docs/Troubleshooting.md
- roles/baseline/defaults/main.yml
Previously the default value for `use-forwarded-headers` was set to true. This has raised a security concern as it allows spoofing source IP via X-Forwarded-For header.
[NGINX Ingress Controller](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#use-forwarded-headers) states the use of `use-forwarded-headers` as follows:
>If true, NGINX passes the incoming X-Forwarded-* headers to upstream. Use this option when NGINX is behind another L7 proxy / load balancer that is setting these headers.
>
>If false, NGINX ignores incoming X-Forwarded-* headers, filling them with the request information it sees. Use this option if NGINX is exposed directly to the internet, or it's behind a L3/packet-based load balancer that doesn't alter the source IP in the packets. …
> feat: (IAC-298) Security update - `use-forwarded-headers` set to false for ingress-ngnix

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Update the client chart version for the nfs-subdir-external-provisioner from 4.0.8 to 4.0.18 so that we will pull the provisioner image from the `registry.k8s.io` container registry instead of the deprecated `k8s.gcr.io` container registry.
|Scenario | DAC deployment tasks | Notes |
|-|-|-|
|Prior to chart version change | "baseline, cluster-logging, viya, install" | Filtered list indicates the only image pulled from k8s.gcr.io as: `k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2`
|After chart version change| "baseline, cluster-logging, cluster-monitoring, viya, install" | All pods stabilized, `sas` and `pg-storage` related PVCs are bound with no errors. Filtered list shows the new CR location for the image above as: …
> fix: Update kubernetes-sigs nfs-provisioner

- examples/multi-tenancy/openldap/openldap-modify-mt-users-groups.yaml
- examples/openldap/openldap-modify-users.yaml
- roles/vdm/templates/generators/openldap-bootstrap-config.yaml
- roles/vdm/templates/generators/openldap-bootstrap-mt-config.yaml
In our example OpenLDAP configuration files, one of the test users has the uidNumber of 1001.
From the SAS Documentation:
> Some pods run system-critical processes under the UID 1001. This UID acts as the owner of CAS server sessions by default and cannot be changed, with one exception: the OpenSearch pods have an option to change the run user. Verify that no user accounts in your LDAP directory are using this UID. This run user is comparable to the sas user account in previous versions of SAS, but it does not exist outside of the container where it runs.
https://go.documentation.sas.com/doc/en/itopscdc/v_038/itopssr/n0bqwd5t5y2va7n1u9xb57lfa9wx.htm#p1l9afrs6ykfjyn1xp09ohsyx392
The PR changes the user1 uidNumber to 7001, I also updated user2 that's in the same group to 7002 to keep it …
> fix: (IAC-358) Update uidNumber for test users in example LDAP confs

- Dockerfile
- docs/CONFIG-VARS.md
- docs/user/Dependencies.md
- roles/baseline/defaults/main.yml
SAS Viya Platform is going to support a range of K8s `1.24-1.26` in cadence `v2023.05`. This PR contains following updates:
- The default kubectl version updated to `1.25.8`
- The default ingress-nginx version updated:
- For K8s version `>= 1.24.X` the default ingress-nginx version is updated to the latest app version: `1.7.0` or chart version: `4.6.0`.
- For K8s version `<= 1.23.X` the default ingress-nginx version is updated to the latest app version: `1.4.0` or chart version: `4.3.0`. **Note**: This is same version from previous release.
Verified SAS Viya Platform deployment is successful on the following scenarios, see details in internal ticket:
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|
|:----|:----|:----|:----|:----|:----| …
> feat: (IAC-1002) Upgrade the default ingress-nginx and kubectl versions to work with K8s 1.26

- Dockerfile
- README.md
- docker-entrypoint.sh
- docs/user/Dependencies.md
- docs/user/Kubeconfig.md
- roles/baseline/tasks/main.yaml
- roles/common/tasks/main.yaml
- roles/vdm/tasks/deploy.yaml
Existing versions of kubectl and custom Kubernetes clients contain provider-specific code to manage authentication between the client and Google Kubernetes Engine. Starting with v1.26, that authentication code will no longer be included as part of the OSS kubectl. The `gke-gcloud-auth-plugin` will fill the gap for the authentication code that is being removed from kubectl.
viya4-deployment supports using two types of GKE kubernetes configuration files, also known as kubeconfig files. The `gke-gcloud-auth-plugin` binary is required to access a GKE clusters when using kubectl 1.26+ with a "provider based" kubernetes configuration file. The "service account and cluster role binding" kubernetes configuration file variant remains the same and still does not require either `gcloud` or the …
> feat: (IAC-696) DAC - Install gke-gcloud-auth-plugin with viya4-deployment for K8s v1.26

- roles/multi-tenancy/tasks/multi-tenant-setup.yaml
On Multi-tenant enabled deployment, offboarding tenants in back-to-back operations failed with JOB_TAG already present error. 
Added the missing `offboard` tag on two tasks which copies and creates the `sas-tenant-offboard-job`.
Verified following scenarios, see details in internal ticket:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|Defaults, SchemaPerTenant Multi-tenant deployment, Onboard 3 tenants and offboard in back-to-back operation | Fast 2020|Viya4 deployment stabilized - tenants correctly onboarded and no failure seen on back-to-back offboard operation |
|2|Defaults, DatabasePerTenant Multi-tenant deployment, Onboard 2 tenants and offboard all at once | Fast 2020| Viya4 deployment stabilized - tenants correctly onboarded and no failure seen on …
> (IAC-1016): fix: Offboarding tenants failure in back-to-back operations

- roles/baseline/defaults/main.yml
Prior to the introduction of the EBS CSI driver, dynamically provisioned EBS persistent volumes were tagged with the cluster name. That made it easy to look at the list of dynamically provisioned volumes in an AWS account and know which cluster they belonged to. Along with the introduction of the EBS CSI driver to dynamically provision volumes, that tagging was lost making it difficult to tell which cluster a volume belonged to.
The EBS CSI driver does support tagging by specifying a cluster name value for the k8sClusterId key in it's helm chart.
This update sets that key value to the cluster name when the EBS CSI driver helm chart is installed.
|Scenario|Method|Task|Provider|k8s version|Cadence|tasks|Deploy method|Remarks|
|-|-|-|-|-|-|-|-|-| …
> fix: (IAC-994) Add K8S Cluster name to dynamic volumes created by EBS CSI Driver

- roles/common/tasks/main.yaml
- roles/vdm/tasks/deploy.yaml
- add multi-tenancy task tags to the set of tasks that will define env_path variable
- add env_path to PATH environment for below the line deployment when running DAC as a docker container. [Below the line deployment](https://github.com/sassoftware/viya4-deployment/pull/430) is an internal use only feature.
See internal ticket for additional details.
|Scenario|Method|kubeconfig |Task|Provider|k8s version|Cadence|tasks|Deploy method|Remarks|
|-|-|-|-|-|-|-|-|-|-|
|1|OOTB|provider based |docker|AWS|1.25.9-eks|fast:2020|baseline,viya,install|deploy command|Deployment command completed successfully and all pods stabilized. V4MT_ENABLE: true, V4MT_MODE: "schema", V4MT_TENANT_IDS: "acme", |
|2|OOTB|provider based |docker|AWS|1.25.9-eks|fast:2020|multi-tenancy,onboard,cas-onboard|deploy command …
> fix: (IAC-1052) add MT tags to the 'Set env_path' tasks

- roles/vdm/tasks/deploy.yaml
- roles/vdm/tasks/postgres/postgres-instance.yaml
- set fact indicating cds-postgres content in storage configmap, use fact to gate references
- Add wait_timeout for Remove Viya task consistent with other similar tasks, this should help reduce the frequency of 120 second task timeout messages that are ignored with current task settings.
See internal ticket for additional details.
|Scenario|Task|method|Provider|k8s version|Cadence|tasks|Deploy method|Remarks|
|-|-|-|-|-|-|-|-|-|
|1|OOTB, internal(default)|Ansible|Azure|1.25.6|fast:2020|baseline,viya,install|deploy command|Deployment command completed successfully and all pods stabilized.|
|2|After scenario # 1 without uninstalling, internal(default,cds-postgres)|Ansible|Azure|1.25.6|fast:2020|viya,install|deploy command|Deployment command completed successfully and all pods stabilized …
> fix: (IAC-975) undefined variable error occurs in set facts for cds-postgres role task

- docs/Troubleshooting.md
Documented the sas-risk-cirrus solutions onboard failure in Troubleshooting.md.
In the current DAC multi-tenancy design the required tenant kubernetes resources or podtemplates are applied alongside cas-onboard task. However, SAS Risk Cirrus Solutions pods expect the podtemplates to be present at the time of onboarding. In SAS Viya Platform cadence v2023.07 the sas-tenant-job was modified to wait for all deployment services to start and return success or error code on exit for any services failures. This change causes the onboard task to fail as the SAS Risk Cirrus Solutions pods aren't able to start.
**Note:** This issue will be fixed in next release, we are document the failure now for awareness.
> docs: (IAC-1118) Document sas-risk-cirrus solutions onboard failure

- Dockerfile
- docs/user/Dependencies.md
Updates the Google Cloud CLI to 440.0.0 to pick up the latest updates
| Scenario | Provider | gcloud version | K8s Version      | Kubeconfig  | Orchestration | Order  | Cadence        |
|----------|----------|----------------|------------------|-------------|---------------|--------|----------------|
| 1        | GCP      | 440.0.0        | v1.26.5-gke.2700 | static      | DO            | * | fast:2020      |
| 2        | GCP      | 440.0.0        | v1.26.5-gke.2700 | auth plugin | DO            | * | stable:2023.07 |
> feat: (IAC-1107) Update Google Cloud CLI to 440.0.0

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
* Update the default `CLUSTER_AUTOSCALER_CHART_VERSION` documentation to indicate that a helm `chartVersion` of 9.29.1 will be used for EKS Kubernetes clusters whose version is >= 1.25
* Update the `chartVersion` value to 9.29.1 that will be used for Kubernetes clusters using versions 1.25 or later
* Remove the `appVersion` value from the `CLUSTER_AUTOSCALER_CONFIG` for the latest `autoScalerVersions` entry, Thomas advised that it can be misleading to provide an `appVersion` since the `appVersion` field is informational only and has no impact on the chart version calculations.
| Scenario | Provider | kubernetes_version | cluster-autoscaler chart version | cluster-autoscaler application Version | order | cadence | notes |
|----------|----------|--------------------|-----------------------|- …
> feat: (IAC-1047) Update to newer release for cluster-autoscaler in EKS

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
* Update the default Ingress-nginx `chartVersion` used to v4.7.1, and `appVersion` used to v1.8.1 for kubernetes cluster versions 1.24 or later  
* Update CONFIG-VARS.md to indicate that the default `INGRESS_NGINX_CHART_VERSION` is 4.7.1 for  kubernetes clusters whose version is >= 1.24
| Scenario | Provider | kubernetes_version | ingress-NGINX version | ingress-nginx helm chart version | order  | cadence   | notes             |
|----------|----------|-------------------------|-----------------|--------|-----------|-------------------|----|
| 1 | Azure | 1.26 (v1.26.6) | 1.8.1 | 4.7.1 | **| ** | DAC ansible, deploy cmd: successful baseline,viya install, all pods stabilized, successful viya_admin login to Viya application |
| 2 | Azure | 1.25 (v1.25.11) | 1.8.1 | 4.7.1 | n/a | n/a | DAC …
> feat: (IAC-1044) update ingress-nginx default to v1.8.1

- docs/CONFIG-VARS.md
Add missing EBS CSI Driver section to the table of contents for CONFIG-VARS.md, https://github.com/sassoftware/viya4-deployment/blob/main/docs/CONFIG-VARS.md
The new "EBS CSI Driver" entry follows the "Cluster Autoscaler" entry
> docs: (IAC-1109) Add EBS CSI Driver section to ToC in CONFIG-VARS.md

- roles/monitoring/files/azure-storageclass.yaml
Updated Azure deployment storageclass to replace storage provisioner deprecated in AKS for K8s v1.26+. This change is based on the change made in the `viya4-monitoring-kubernetes` repo [PR #481](https://github.com/sassoftware/viya4-monitoring-kubernetes/pull/481/files)
Verified logging and monitoring component deployed correctly as expected using the new provisioner on the following scenarios, see details in internal ticket
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|
|:----|:----|:----|:----|:----|:----|
|1|OOTB|Azure|fast:2020|1.25|ansible, DO: true|
|2|OOTB|Azure|fast:2020|1.26|ansible, DO: false|
> feat: (IAC-1003) Update deprecated provisioner in V4M Azure storageclass

- docs/user/Multi-Tenancy.md
- playbooks/playbook.yaml
- roles/multi-tenancy/defaults/main.yml
- roles/multi-tenancy/tasks/main.yaml
- roles/multi-tenancy/tasks/multi-tenant-onboard-offboard.yaml
- roles/multi-tenancy/tasks/multi-tenant-setup.yaml
- roles/multi-tenancy/tasks/onboard-offboard-cas-servers.yaml
- roles/multi-tenancy/tasks/tenant-pod-templates.yaml
- roles/vdm/tasks/assets.yaml
- roles/vdm/tasks/deploy.yaml
- roles/vdm/tasks/main.yaml
- roles/vdm/tasks/sasdeployment_custom_resource.yaml
The new/improved DAC multi-tenant steps would be:
1. After the initial provider deployment has stabilized, run the onboard command
2. The `onboard` command would do following:
- Copy all the required files and update all the required variables
- Do the required steps for pod-templates and run SAS Software deploy steps to apply tenant pod-templates
- Wait for ~7 mins
- Apply the tenant onboard step and run sas-tenant-onboard job
- Wait for sas-tenant-onboard job to reach running state. 
-  Wait for 2 more mins for `sas-tenant-onboard` job to trigger the mid-tier services restart
4. Continue with `cas-onboard` steps.
|Scenario|Description|Order Cadence|Deploy method|Verification|
|:----|:----|:----|:----|:----|
|1|Multi-tenancy …
> feat: (IAC-1108) Multi-tenancy process change - apply podtemplates before running onboard

- Dockerfile
- docs/user/Dependencies.md
- roles/baseline/defaults/main.yml
SAS Viya Platform will support a range of K8s `1.25-1.27` in cadence `2023.09`. 
This PR contains following updates:
- The default kubectl version updated to `1.26.8`
- remove ingress-nginx AppVersion values per previous decision
Verified SAS Viya Platform deployment is successful on the following scenarios
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|Notes|
|:----|:----|:----|:----|:----|:----|:----|
|1|OOTB|AWS (1.27.3-eks) |fast:2020|1.27|ansible, DO: false| All pods stable in deployment, successful viya_admin login to Viya Application.
|2|OOTB|AWS (1.26.7-eks) |stable 2023.08|1.26|ansible, DO: true| All pods stable in deployment.
|3|OOTB|Azure (1.25.11) |stable 2023.06|1.25|docker, DO: false| All pods stable in deployment, successful viya_admin login to Viya …
> feat: (IAC-1147) DAC - Support K8s 1.27 in 2023.09

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Update the default version of cert-manager to 1.13.1
cert-manager 1.13.1 is compatible with kubernetes versions 1.23 → 1.28, see supported
releases: https://cert-manager.io/docs/releases/
There are no breaking changes from the original default of 1.11.0 to 1.13.1, see the upgrade documentation here:
* https://cert-manager.io/docs/releases/upgrading/upgrading-1.11-1.12/
* https://cert-manager.io/docs/releases/upgrading/upgrading-1.12-1.13
| Scenario | Task                      | Provider | K8s                 | V4_CFG_TLS_GENERATOR | CERT_MANAGER_CHART_VERSION | V4_CFG_TLS_MODE | V4_CFG_TLS_CERT/KEY/TRUSTED_CA_CERTS                               | order | cadence   |
|----------|---------------------------|----------|---------------------|----------------------|----------------------------| …
> feat: (IAC-1170) Update Default CERT_MANAGER_CHART_VERSION to 1.13.1

- roles/vdm/tasks/deploy.yaml
* Change the value used for the PATH environment variable in the DAC Deploy SAS Viya Ansible tasks so that the path to binaries in the ORCHESTRATION_TOOLING_PATH, including kubectl, come prior to the path for binaries present in the filesystem from DAC content.
PATH value change within the task is from this:
`PATH: "{{ env_path + ':' + ORCHESTRATION_TOOLING_PATH }}"`
to this:
`PATH: "{{ ORCHESTRATION_TOOLING_PATH + ':' + env_path }}"`
| Scenario | Provider | kubernetes_version | create_static_kubeconfig | order | cadence | notes |
|----------|----------|--------------------|--------------------------|-------|---------|-------|
| 1 | AWS | 1.26 (v1.26.7-eks) | false | 2023.08 | stable | SAS Viya pods are running and stabilized, Successful login to SASDrive app as viya_admin, successful …
> fix: (IAC-1169) deploy orchestration cmd in DAC docker container fails running DAC's kubectl binary

- roles/common/tasks/main.yaml
To enable the North-South traffic again in Azure, a task was added to include `aks_pod_cidr` in `LOADBALANCER_SOURCE_RANGES`.
For more details on this change see description of [Azure PR #341](https://github.com/sassoftware/viya4-iac-azure/pull/341).
Verified following scenarios, for details see internal ticket:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|OOTB, Defaults|Fast 2020|`aks_pod_cidr` is read from tfstate file and added to `LOADBALANCER_SOURCE_RANGES`. Viya4 deployment stabilized, applications were accessible and the example proc http to query an endpoint was successful |
|2|`aks_pod_cidr` was added to `LOADBALANCER_SOURCE_RANGES` in ansible-vars|Fast 2020|`aks_pod_cidr` was not read from tfstate file. `LOADBALANCER_SOURCE_RANGES` were set …
> fix: (IAC-1072) Add AKS pod cidr to LOADBALANCER_SOURCE_RANGES

- docs/CONFIG-VARS.md
- docs/Troubleshooting.md
- docs/user/PostPostgreSQLDataTransfer_Experimental.md
- roles/baseline/defaults/main.yml
- roles/common/tasks/main.yaml
- roles/vdm/tasks/deploy.yaml
- #494 
- #492 
- #496 
- #497
- #498
> 6.13.0 - October 19, 2023

- Dockerfile
- docs/user/Dependencies.md
- requirements.txt
- requirements.yaml
Updates 3rd party dependencies to resolve the security vulnerabilities. Users of the Dockerfile will automatically have these updated dependencies installed, and users who directly run this project on the host will need to update the dependencies themselves.
Update summary:
* `ansible:` 8.0.0 -> 8.6.0
* No major version change, `ansible-core` updated from 2.15.0 -> 2.15.6
* `helm:` 3.12.0 -> 3.13.2
Verified following scenario, see details in the internal ticket:
| Scenario | Provider | K8s Version | Order  | Cadence   | 
|----------|----------|-------------|--------|-----------|
| 1        | Azure     | v1.26.10    | ****** | fast:2020 |
> feat: (IAC-1194) Update dependencies to resolve security vulnerabilities

- Dockerfile
- docs/CONFIG-VARS.md
- docs/user/Dependencies.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/ingress-nginx.yaml
This PR updates the kubectl version to `1.27` and also updates the ingress-nginx version to 1.9.5 which supports the K8 versions: `1.28, 1.27, 1.26, 1.25`.
*Note:* The logic was updated to support the latest version of ingress by default. For any K8s version out of range for the given ingress version would now need to specify `INGRESS_NGINX_CHART_VERSION` to avoid error.
For example: The latest ingress Helm Chart Version is `4.9.0` which supports K8s range `1.28, 1.27, 1.26, 1.25`. For K8s version < 1.25.X, user needs to specify `INGRESS_NGINX_CHART_VERSION`. Not specifying the `INGRESS_NGINX_CHART_VERSION` will result in following error:
```
fatal: [localhost]: FAILED! => {
"changed": false,
"msg": "INGRESS_NGINX_CHART_VERSION isn't set when K8s version is < 1.25."
}
```
Verified …
> feat: (IAC-1266) (IAC-1186) Update kubectl to 1.27 and add support for ingress-nginx v1.9.X

- Dockerfile
- docs/user/Dependencies.md
Update the Google Cloud CLI version to 460.0.0 so that it's in sync with the viya4-iac-gcp repo
| Scenario | Provider | kubernetes_version  | order  | cadence   | notes           |
|----------|----------|---------------------|--------|-----------|-----------------|
| 1        | GCP      | v1.27.9-gke.1092000 | ****** | fast:2020 | OOTB deployment |
> feat: (IAC-1329) Update Google Cloud CLI version to be in sync with viya4-iac-gcp

- requirements.txt
- roles/vdm/templates/transformers/sas-storageclass.yaml
- Avoid applying the sas-storage.yaml patchTransformer for the sas-airflow component so that DAC can successfully build the deployment manifest without encountering the fatal error indicated in the subject.
- Pin urllib3 to latest 1.26.x version. Use of urllib3>= 2.1.0 leads to the following error getting the orchestration tooling image when running DAC with a locally installed Ansible binary.
> TASK [vdm : Orchestration tooling - orchestration tooling image] ***************
> task path: ~/gitlab.sas.com/DOPE/ansible-marketplace/viya4-deployment/public/roles/orchestration-common/tasks/orchestration_tooling.yaml:153
> fatal: [localhost]: FAILED! => changed=false
>   msg: 'Error connecting: Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument …
> fix: (IAC-1335) Resolve: doc is missing path: "/spec/volumeClaimTemplates/0/spec/storageClassName" error

- Dockerfile
- docs/user/Dependencies.md
- requirements.txt
- requirements.yaml
Updates 3rd party dependencies to resolve security findings from our scanning tool. Consumers of the Dockerfile will automatically have these updated dependencies installed, and users who directly run this project on this host will need to update the dependencies themselves.
Update summary:
* `ansible` 8.6.0 -> 9.1.0
* Not a major change, while the bundled collections are updated, `ansible-core` goes from 2.15.8 -> 2.16.1
* https://github.com/ansible/ansible/blob/stable-2.15/changelogs/CHANGELOG-v2.15.rst
* https://github.com/ansible/ansible/blob/stable-2.16/changelogs/CHANGELOG-v2.16.rst
* `community.docker` 2.7.0 -> 2.7.8
* Not a major change, updated to latest available minor version
* https://github.com/ansible-collections/community.docker/blob/stable-2/CHANGELOG.rst 
* `helm` 3.13.2 …
> feat: (IAC-1310) Dependency version update to resolve security vulnerability

- roles/monitoring/tasks/main.yaml
Fix the `V4M - ensure supported value for V4M_ROUTING` task to that the intersect function has the correct input format.
It looks like when we updated the `ansible` version from 9.1.0->8.6.0 this problem started appearing. That version bump causes the `ansible-core` version to go from 2.15->2.16.
Looking at the release notes for 2.16 it looks like there was a bug fix around set filters that changed its behavior. We are updating this function so we don't rely on its previous "bugged" behavior.
https://github.com/ansible/ansible/blob/stable-2.16/changelogs/CHANGELOG-v2.16.rst#v2-16-0
From CHANGELOG:
> * Set filters intersect, difference, symmetric_difference and union now always return a list, never a set. Previously, a set would be returned if the inputs were a hashable type such as str, …
> fix: (IAC-1362) Fix the V4M_ROUTING Validation Task

- docs/user/SingleStore.md
* Add a new section to docs/user/SingleStore.md for Customizing SingleStore Deployment Overlays for orders including SAS Viya with SingleStore for stable cadence versions 2023.10 and later.
* Added a new section heading to docs/user/SingleStore.md for Customizing SingleStore Deployment Overlays for orders including SAS Viya with SingleStore for LTS versions 2023.03 and earlier.
| Scenario | Provider | method | kubernetes_version | Cadence version | order | notes |
|----------|----------|--------|--------------------|-----------------|-------|--------|
| 1 | Azure | Ansible | 1.27 | fast:2020 | *| Used customizing instructions under heading _SAS Viya and SingleStore stable:2023.10 and later_ in [SingleStore.md](https://github.com/sassoftware/viya4-deployment/compare/staging...docs/iac-1302? …
> docs: (IAC-1302) Deployment fails when following DAC SingleStore.md

- roles/monitoring/templates/host-based/user-values-prom-operator.yaml
- roles/monitoring/templates/path-based/user-values-prom-operator.yaml
Update the `Prometheus.prometheusSpec.alertingEndpoints` stanza in the `user-values-prom-operator.yaml` file for both our host-based and path-based templates. SAS Viya Monitoring has in an upcoming release that will be a breaking change for some users, the changes in the PR will be compatible with both the current configuration and the coming changes and prevent users from being impacted.
For additional details on the change from `viya4-monitoring-kubernetes` see the announcement underneath the notes for [Version 1.2.22 (13FEB2024)](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/main/CHANGELOG.md#version-1222-13feb2024). The release of their change is tentatively scheduled the 1.2.23 release (expected mid-March).
| Scenario | Provider | K8s Version | V4M_ROUTING | Order …
> feat: (IAC-1375) Edit Ingress Definitions for Alertmanager To Adapt Changes From Viya Monitoring

- docs/CONFIG-VARS.md
Doc update about users needing to set `V4_CFG_SITEDEFAULT` if they opt not to use the embedded LDAP server.
> docs: (IAC-1294) Add Note about sitedefault When Not Using Embedded LDAP

- docs/user/Dependencies.md
Dependencies.md file had an incorrect entry for `kubernetes.core` version. In the requirements.yaml, `kubernetes.core` version 3.0.0 is being installed and the doc was accidentally pointing to wrong version 3.0.1. This PR corrects that.
> docs: (IAC-1236) Updated Dependencies.md file with correct versions

- Dockerfile
Fix the `gcp_cli_version` argument value in the Dockerfile so that it has a Debian revision
| Scenario | Provider | K8s Version                 | gcloud version | Order  | Cadence   | Notes                 |
|----------|----------|-----------------------------|----------------|--------|-----------|-----------------------|
| 1        | GCP      | 1.27 (v1.27.11-gke.1202000) | 464.0.0        | ****** | fast:2020 | OOTB - external image |
> fix: (IAC-1420) add debian revision to gcp_cli_version arg in Dockerfile

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
Update the default version of cert-manager to 1.14.4
cert-manager 1.14.4 is compatible with kubernetes versions 1.24 → 1.29, see supported
releases: https://cert-manager.io/docs/releases/
There are no breaking changes from the original default of 1.13.1 to 1.14.4, see the upgrade documentation here:
* https://cert-manager.io/docs/releases/upgrading/upgrading-1.13-1.14/
| Scenario | Task                      | Provider | K8s                  | V4_CFG_TLS_GENERATOR | CERT_MANAGER_CHART_VERSION | V4_CFG_TLS_MODE | V4_CFG_TLS_CERT/KEY/TRUSTED_CA_CERTS                               | order  | cadence   |
|----------|---------------------------|----------|----------------------|----------------------|----------------------------|-----------------|------------------------------------------------- …
> feat: (IAC-1372) Update Default CERT_MANAGER_CHART_VERSION to 1.14.4

- Dockerfile
- docs/CONFIG-VARS.md
- docs/user/Dependencies.md
- roles/baseline/defaults/main.yml
- roles/baseline/tasks/cluster-autoscaler.yaml
This PR updates the default versions of ingress-nginx, cluster-autoscaler and kubectl to add support for K8s 1.29
- Default ingress-nginx chart version is updated to `4.9.1`
- Default cluster-autoscaler chart version is updated to `9.36.0`
- Default kubectl version is updated to `1.28.7`
Code to set default version of `CLUSTER_AUTOSCALER_CHART_VERSION` was simplified as K8s v1.24 is now out standard support for all the cloud providers. For users using K8s v1.24 to do LTS cadence version will now have to specify the CLUSTER_AUTOSCALER_CHART_VERSION in their `ansible-var.yaml` file. CONFIG_VARS.md file note is updated to guide user about the same.
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|Notes| …
> feat: (IAC-1344) (IAC-1363) Add support for K8s 1.29

- Dockerfile
- docs/user/Dependencies.md
Updated the gcloud version to 471.0.0 to sync up with the `viya4-iac-gcp` project
| Scenario | Provider | kubernetes_version  | Order  | Cadence   | Notes |
|----------|----------|---------------------|--------|-----------|-------|
| 1        | GCP      | v1.28.8-gke.1095000 | * | fast:2020 | OOTB  |
> feat: (IAC-1424) Update Google Cloud CLI version to be in sync with viya4-iac-gcp

- docs/Troubleshooting.md
Documentation around tagging your EC2 load balancers which get provisioned when `ingress-nginx` is installed.
> docs: (IAC-1337) Add EC2 LB Tagging Documentation

- Dockerfile
- docs/user/Dependencies.md
Updated the gcloud version to 472.0.0 to sync up with the `viya4-iac-gcp` project
| Scenario | Provider | kubernetes_version  | Order  | Cadence   | Notes |
|----------|----------|---------------------|--------|-----------|-------|
| 1        | GCP      | v1.28.9-gke.1000000 | ****** | fast:2020 | OOTB  |
> feat: (IAC-1449) Update Google Cloud CLI version to be in sync with viya4-iac-gcp

- docs/user/SingleStore.md
Update README.md to include Red Hat OpenShift as one of the platform types that SAS with SingleStore can be deployed on. Explicitly state that SAS does not support Infrastructure as Code (IaC) on OpenShift.
> docs: (SINGLESTORE-2165) Update SingleStore.md

- roles/monitoring/tasks/main.yaml
Updated the uninstallation behavior when `V4_CFG_MANAGE_STORAGE:true` & `PROVIDER in ["azure","aws","gcp"]` so that the v4m storage class will not be removed if there are still PVs using it. If no PVs are making use of the v4m sc then it will also be removed. This prevents the v4m SC from being removed if a user just uninstalls only logging or only monitoring.
| Scenario | Provider | Kubernetes Version   | Install                                                  | Uninstall 1                                                | Uninstall 2                                                    |
|----------|----------|----------------------|----------------------------------------------------------|------------------------------------------------------------|--------------------------------------- …
> fix: (PSKD-398) Update v4m storage class deletion behavior

- Dockerfile
- docs/user/Dependencies.md
Updated files necessary to change kubectl version to 1.29.7 in support of K8S 1.30.
This PR updates the default version of kubectl to add support for K8s 1.30
- Default kubectl version is updated to `1.29.7`
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|Notes|
|:----|:----|:----|:----|:----|:----|:----|
|1|OOTB|Azure|stable:2024.07|1.28|docker, DO: false||
|2|OOTB|Azure|stable:2024.07|1.29|docker, DO: false| New default kubectl|
|3|OOTB|Azure|stable:2024.07|1.30|ansible, DO: true| Overwrite kubectl version in the DO|
> feat: add support for K8S 1.30 (PSKD-518)

- roles/vdm/templates/transformers/dataserver-transformer.yaml
This PR adds an annotation to deployments that are using an external postgres database.  The presence of the annotation will gate behaviour of the data server operator.
Verified following scenarios
|Scenario|Task|Provider|Cadence|kubernetes_version|Database|Notes|
|:----|:----|:----|:----|:----|:----|:----|
|1|OOTB|Azure|stable:2024.07|1.28|default: external| Annotation appears in sasdeployment.yaml manifest|
|2|OOTB|Azure|stable:2024.07|1.29|default: internal| Annotation does NOT appear in sasdeployment.yaml manifest|
> feat: add annotation for external database (PSKD-407)

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
This PR updates the ingress-nginx version to `v1.11.1` which supports the K8 versions: 1.30, 1.29 1.28, 1.27 and 1.26.
| Scenario | Cloud Provider | Cadence             | Ingress-NGINX version | Kubernetes version | Notes                                      |
|----------|----------------|---------------------|-----------------------|--------------------|--------------------------------------------|
| 1        | AWS            | stable:2024.07 R/P  | v1.11.1               | v1.29              | Successful deployment, all pods Running and stable |
| 2        | Azure          | stable:2024.07 R/P  | v1.11.1                | v1.28              | Successful deployment, all pods Running and stable |
| 3        | Azure          | n/a                 | v1.11.1               | v1.30 …
> feat: (PSKD-503) Update DaC ingress-nginx version for K8s 1.30 support

- README.md
- docs/CONFIG-VARS.md
- docs/Troubleshooting.md
- docs/user/AnsibleCloudAuthentication.md
- docs/user/AnsibleUsage.md
- docs/user/DockerUsage.md
- docs/user/PostgreSQL.md
Google naming conventions have changed. Google Cloud Platform is now called Google Cloud. This PR makes the required updates to adhere the new naming convention wherever applicable.
See more details here: https://cloud.google.com/blog/topics/developers-practitioners/introducing-new-homepage-google-cloud
> docs: (PSKD-710) Update GCP refs in documentation

- roles/vdm/tasks/workload_orchestrator.yaml
Starting SAS Viya cadence 2024.07 the SAS Workload Orchestrator Configuration file location changed. This PR updates the path based on specified cadence version.
Verified following scenarios with `V4_DEPLOYMENT_OPERATOR_ENABLED: false` and `V4_WORKLOAD_ORCHESTRATOR_ENABLED: false`.
|Scenario|Task|Provider|Cadence|Deploy method|
|:----|:----|:----|:----|:----|
|1|OOTB|Azure|fast:2020|ansible|
|2|OOTB|Azure|stable:2024.06|ansible|
|3|OOTB|Azure|lts:2023.03|ansible|
> fix: (PSKD-640) Fixed file path for Workload Orchestrator

- Dockerfile
- docs/user/Dependencies.md
Update files necessary to change kubectl version to 1.30.6 in support of K8S 1.31.
This PR updates the default version of kubectl to add support for K8s 1.31
- Default kubectl version is updated to `1.30.6`
|Scenario|Provider|kubernetes_version|Order|Cadence|Notes|
|:----|:----|:----|:----|:----|:----|
|1|Azure|1.31.2|***|fast:2020|OOTB, external Postgres Database, front-door TLS. Overwrite kubectl version in DO|
|2|GCP|1.29.10|***|fast:2020|OOTB, external Postgres Database, front-door TLS. DO: true|
|3|AWS|1.30.6|***|fast:2020|Used local tooling. Internal Postgres Database, full-stack TLS. DO: false|
> feat: (PSKD-813) add support for K8s 1.31

- roles/vdm/tasks/tls.yaml
Fixes issue 580 by adding `hidden: true` to the find module to restore v4_cfg_tls_trusted_ca_certs  functionality
> 580:  search for hidden files in cacerts dir

- Dockerfile
- roles/orchestration-common/tasks/orchestration_tooling.yaml
This PR changes how the Dockerfile installs skopeo. The version in the apt repository is outdated, so this will build it from the source and copy it into the Docker image.
Note: Skopeo is only used by the Docker image. Consumers that don't use the Docker image will be unaffected.
|Scenario|Provider|Order|Cadence|Notes|
|:----|:----|:----|:----|:----|
|1|Azure|***|fast:2020|OOTB, internal DB. DO: true|
|2|GCP|***|fast:2020|OOTB, internal DB. DO: false|
|3|GCP|***|fast:2020|Used local tooling. Skopeo is only used by the Docker Image, so this is unaffected.|
> feat: (PSKD-881) Update Skopeo Installation

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- Update default version of cert-manager installed to v1.16.2
- Replaced deprecated `installCRDs` Helm option value with supported option
| Scenario | Provider | K8S version | DAC method | Installed CERT-MANAGER_CHART_VERSION | CERT_MANAGER_CHART_VERSION | order | cadence | Notes |
|----------|----------|-------------|------------|-------------------------------------|-----------------------------|-------|---------|-------|
|1|Azure|1.29|docker|1.14.4|1.16.2|n/a|n/a|Running DaC with the default version of 1.16.2 and "baseline,install" results in a successful cert-manager upgrade to version v1.16.2|
| 2        | AWS      | 1.30        | docker     | None                                | 1.16.2                      | *     | n/a     | Resulting error message. `installCRDs` value is the …
> feat: (PSKD-792) Update default version of cert-manager to v1.16.2

- docs/CONFIG-VARS.md
- roles/baseline/defaults/main.yml
- Update the default version of the `ingress-nginx` Helm chart to use v4.12.0 for K8s >= v1.28 in order to support K8s 1.31
- Update the default for `INGRESS_NGINX_CHART_VERSION` in CONFIG-VARS.md file to be 4.12.0
| Scenario | Provider | K8s version | ingress-nginx chart version | Cadence       | relevant ingress-nginx config map values                          | Notes                                                                 |
|----------|----------|-------------|-----------------------------|---------------|-------------------------------------------------------------------|-----------------------------------------------------------------------|
| 1        | Azure    | 1.30.6      | (default) 4.12.0            | stable:2024.12| annotations-risk-level: Critical …
> feat: (PSKD-1006) Use ingress-nginx v1.12 for K8s 1.31 support

- docs/CONFIG-VARS.md
The Crunchy team has recommended adding this help text to the updates made under #594 when setting the Crunchy storage class reclaim policy to `Retain`.
> docs: Use block storage for Crunchy Postgres (PSKD-1282)

- Dockerfile
We're bumping the helm version to address a high security vulnerability found in the prisma scan. The vulnerability found is with golang.org/x/net v0.26.0. Using v3.17.1 version of helm gets us to v0.33.0 of golang.org/x/net where the vulnerability has been addressed.
We're also refreshing the versions of other binaries included in the image. Here is a summary.
Updates 3rd party dependencies. Consumers of the Dockerfile will automatically have these updated dependencies installed. Users who directly run this project on this host will need to update the dependencies themselves.
**Binaries**
* `kubectl` 1.30.6 -> 1.30.10
* `helm` 3.16.2 -> 3.17.1
* `aws_cli_version` 2.17.58 -> 2.24.16
* `gcp_cli_version` 496.0.0 -> 513.0.0
| Scenario | Provider | Kubernetes Version | Order | Cadence | Notes …
> chore: (PSKD-1406) Dependency Version Bumps

- docs/CONFIG-VARS.md
RabbitMQ fails if
EBS_CSI_RABBITMQ_STORAGE_CLASS_VOLUME_TYPE: gp3
and
EBS_CSI_RABBITMQ_STORAGE_CLASS_IOPSPERGB > 500
> docs: document max IOPS per volume for gp3 is 500 (PSKD-1648)

- CONTRIBUTING.md
Adding documentation steps to the CONTRIBUTING.md on how to open a PR via forking a repository
> docs: steps to open a PR (PSKD-1751)

- docs/user/MigrationSteps-v9.md
The viya4-deployment (DaC) project recently updated its storage strategy, replacing the nfs-subdir-external-provisioner with the nfs.csi.k8s.io provisioner.
This PR adds a step-by-step migration guide to help transition from the legacy nfs-subdir-external-provisioner to the CSI-based csi-driver-nfs in Kubernetes environments.
> docs: add v9.0.0 migration guide with CSI NFS Driver (PSCLOUD-2)

- roles/baseline/tasks/ingress-nginx.yaml
set ingress-nginx chart version dynamically based on cadence version
- Added conditional logic to set INGRESS_NGINX_CHART_VERSION to 4.12.1 when
V4_CFG_CADENCE_VERSION <= 2025.07, otherwise default to 4.13.0.
- Ensures correct chart version is used during Helm deployment based on cadence schedule.
> feat: set ingress-nginx chart version dynamically based on cadence version (PSCLOUD-99, PSCLOUD-158)

- docs/CONFIG-VARS.md
**PR Description**
This PR updates the documentation links for the Metrics Server configuration variables.
- The current documentation references the Bitnami chart for METRICS_SERVER_CHART_URL and METRICS_SERVER_CHART_VERSION.
- However, based on our IaC code ([main.yml#L29](https://github.com/sassoftware/viya4-deployment/blob/431881b8175ef8282981958ba20447a246992786/roles/baseline/defaults/main.yml#L29)), we are not using the Bitnami chart. Instead, we are pulling from the official Kubernetes SIGs Metrics Server repo:
- Repo: https://kubernetes-sigs.github.io/metrics-server/
- Artifact Hub: https://artifacthub.io/packages/helm/metrics-server/metrics-server
**Changes Made**
Updated CONFIG-VARS.md to replace Bitnami references with the correct Kubernetes SIGs Metrics Server chart and …
> fix: update CONFIG-VARS.md for metric server (PSCLOUD-98)

- docs/user/SingleStore.md
(PSCLOUD-126) Update viya4-deployment READMEs to include new SAS SpeedyStore Name
The official name of 'SAS with Singlestore' changed to 'SAS SpeedyStore'
> docs: (PSCLOUD-126) Update viya4-deployment READMEs to include new SAS SpeedyStore Name
